package enrich

var countryNames = map[string][2]string{
	"AC": {"Ascension Island", "Ascension Adası"},
	"AD": {"Andorra", "Andorra"},
	"AE": {"United Arab Emirates", "Birleşik Arap Emirlikleri"},
	"AF": {"Afghanistan", "Afganistan"},
	"AG": {"Antigua & Barbuda", "Antigua ve Barbuda"},
	"AI": {"Anguilla", "Anguilla"},
	"AL": {"Albania", "Arnavutluk"},
	"AM": {"Armenia", "Ermenistan"},
	"AN": {"Curaçao", "Curaçao"},
	"AO": {"Angola", "Angola"},
	"AQ": {"Antarctica", "Antarktika"},
	"AR": {"Argentina", "Arjantin"},
	"AS": {"American Samoa", "Amerikan Samoası"},
	"AT": {"Austria", "Avusturya"},
	"AU": {"Australia", "Avustralya"},
	"AW": {"Aruba", "Aruba"},
	"AX": {"Åland Islands", "Åland Adaları"},
	"AZ": {"Azerbaijan", "Azerbaycan"},
	"BA": {"Bosnia & Herzegovina", "Bosna-Hersek"},
	"BB": {"Barbados", "Barbados"},
	"BD": {"Bangladesh", "Bangladeş"},
	"BE": {"Belgium", "Belçika"},
	"BF": {"Burkina Faso", "Burkina Faso"},
	"BG": {"Bulgaria", "Bulgaristan"},
	"BH": {"Bahrain", "Bahreyn"},
	"BI": {"Burundi", "Burundi"},
	"BJ": {"Benin", "Benin"},
	"BL": {"St. Barthélemy", "Saint Barthelemy"},
	"BM": {"Bermuda", "Bermuda"},
	"BN": {"Brunei", "Brunei"},
	"BO": {"Bolivia", "Bolivya"},
	"BQ": {"Caribbean Netherlands", "Karayip Hollandası"},
	"BR": {"Brazil", "Brezilya"},
	"BS": {"Bahamas", "Bahamalar"},
	"BT": {"Bhutan", "Butan"},
	"BU": {"Myanmar (Burma)", "Myanmar (Burma)"},
	"BV": {"Bouvet Island", "Bouvet Adası"},
	"BW": {"Botswana", "Botsvana"},
	"BY": {"Belarus", "Belarus"},
	"BZ": {"Belize", "Belize"},
	"CA": {"Canada", "Kanada"},
	"CC": {"Cocos (Keeling) Islands", "Cocos (Keeling) Adaları"},
	"CD": {"Congo - Kinshasa", "Kongo - Kinşasa"},
	"CF": {"Central African Republic", "Orta Afrika Cumhuriyeti"},
	"CG": {"Congo - Brazzaville", "Kongo - Brazavil"},
	"CH": {"Switzerland", "İsviçre"},
	"CI": {"Côte d’Ivoire", "Côte d’Ivoire"},
	"CK": {"Cook Islands", "Cook Adaları"},
	"CL": {"Chile", "Şili"},
	"CM": {"Cameroon", "Kamerun"},
	"CN": {"China", "Çin"},
	"CO": {"Colombia", "Kolombiya"},
	"CP": {"Clipperton Island", "Clipperton Adası"},
	"CQ": {"Sark", "CQ"},
	"CR": {"Costa Rica", "Kosta Rika"},
	"CS": {"Serbia", "Sırbistan"},
	"CU": {"Cuba", "Küba"},
	"CV": {"Cape Verde", "Cabo Verde"},
	"CW": {"Curaçao", "Curaçao"},
	"CX": {"Christmas Island", "Christmas Adası"},
	"CY": {"Cyprus", "Kıbrıs"},
	"CZ": {"Czechia", "Çekya"},
	"DD": {"Germany", "Almanya"},
	"DE": {"Germany", "Almanya"},
	"DG": {"Diego Garcia", "Diego Garcia"},
	"DJ": {"Djibouti", "Cibuti"},
	"DK": {"Denmark", "Danimarka"},
	"DM": {"Dominica", "Dominika"},
	"DO": {"Dominican Republic", "Dominik Cumhuriyeti"},
	"DY": {"Benin", "Benin"},
	"DZ": {"Algeria", "Cezayir"},
	"EA": {"Ceuta & Melilla", "Ceuta ve Melilla"},
	"EC": {"Ecuador", "Ekvador"},
	"EE": {"Estonia", "Estonya"},
	"EG": {"Egypt", "Mısır"},
	"EH": {"Western Sahara", "Batı Sahra"},
	"ER": {"Eritrea", "Eritre"},
	"ES": {"Spain", "İspanya"},
	"ET": {"Ethiopia", "Etiyopya"},
	"EU": {"European Union", "Avrupa Birliği"},
	"EZ": {"Eurozone", "Euro Bölgesi"},
	"FI": {"Finland", "Finlandiya"},
	"FJ": {"Fiji", "Fiji"},
	"FK": {"Falkland Islands", "Falkland Adaları"},
	"FM": {"Micronesia", "Mikronezya"},
	"FO": {"Faroe Islands", "Faroe Adaları"},
	"FR": {"France", "Fransa"},
	"FX": {"France", "Fransa"},
	"GA": {"Gabon", "Gabon"},
	"GB": {"United Kingdom", "Birleşik Krallık"},
	"GD": {"Grenada", "Grenada"},
	"GE": {"Georgia", "Gürcistan"},
	"GF": {"French Guiana", "Fransız Guyanası"},
	"GG": {"Guernsey", "Guernsey"},
	"GH": {"Ghana", "Gana"},
	"GI": {"Gibraltar", "Cebelitarık"},
	"GL": {"Greenland", "Grönland"},
	"GM": {"Gambia", "Gambiya"},
	"GN": {"Guinea", "Gine"},
	"GP": {"Guadeloupe", "Guadeloupe"},
	"GQ": {"Equatorial Guinea", "Ekvator Ginesi"},
	"GR": {"Greece", "Yunanistan"},
	"GS": {"South Georgia & South Sandwich Islands", "Güney Georgia ve Güney Sandwich Adaları"},
	"GT": {"Guatemala", "Guatemala"},
	"GU": {"Guam", "Guam"},
	"GW": {"Guinea-Bissau", "Gine-Bissau"},
	"GY": {"Guyana", "Guyana"},
	"HK": {"Hong Kong SAR China", "Çin Hong Kong ÖİB"},
	"HM": {"Heard & McDonald Islands", "Heard Adası ve McDonald Adaları"},
	"HN": {"Honduras", "Honduras"},
	"HR": {"Croatia", "Hırvatistan"},
	"HT": {"Haiti", "Haiti"},
	"HU": {"Hungary", "Macaristan"},
	"HV": {"Burkina Faso", "Burkina Faso"},
	"IC": {"Canary Islands", "Kanarya Adaları"},
	"ID": {"Indonesia", "Endonezya"},
	"IE": {"Ireland", "İrlanda"},
	"IL": {"Israel", "İsrail"},
	"IM": {"Isle of Man", "Man Adası"},
	"IN": {"India", "Hindistan"},
	"IO": {"British Indian Ocean Territory", "Britanya Hint Okyanusu Toprakları"},
	"IQ": {"Iraq", "Irak"},
	"IR": {"Iran", "İran"},
	"IS": {"Iceland", "İzlanda"},
	"IT": {"Italy", "İtalya"},
	"JE": {"Jersey", "Jersey"},
	"JM": {"Jamaica", "Jamaika"},
	"JO": {"Jordan", "Ürdün"},
	"JP": {"Japan", "Japonya"},
	"KE": {"Kenya", "Kenya"},
	"KG": {"Kyrgyzstan", "Kırgızistan"},
	"KH": {"Cambodia", "Kamboçya"},
	"KI": {"Kiribati", "Kiribati"},
	"KM": {"Comoros", "Komorlar"},
	"KN": {"St. Kitts & Nevis", "Saint Kitts ve Nevis"},
	"KP": {"North Korea", "Kuzey Kore"},
	"KR": {"South Korea", "Güney Kore"},
	"KW": {"Kuwait", "Kuveyt"},
	"KY": {"Cayman Islands", "Cayman Adaları"},
	"KZ": {"Kazakhstan", "Kazakistan"},
	"LA": {"Laos", "Laos"},
	"LB": {"Lebanon", "Lübnan"},
	"LC": {"St. Lucia", "Saint Lucia"},
	"LI": {"Liechtenstein", "Liechtenstein"},
	"LK": {"Sri Lanka", "Sri Lanka"},
	"LR": {"Liberia", "Liberya"},
	"LS": {"Lesotho", "Lesotho"},
	"LT": {"Lithuania", "Litvanya"},
	"LU": {"Luxembourg", "Lüksemburg"},
	"LV": {"Latvia", "Letonya"},
	"LY": {"Libya", "Libya"},
	"MA": {"Morocco", "Fas"},
	"MC": {"Monaco", "Monako"},
	"MD": {"Moldova", "Moldova"},
	"ME": {"Montenegro", "Karadağ"},
	"MF": {"St. Martin", "Saint Martin"},
	"MG": {"Madagascar", "Madagaskar"},
	"MH": {"Marshall Islands", "Marshall Adaları"},
	"MK": {"North Macedonia", "Kuzey Makedonya"},
	"ML": {"Mali", "Mali"},
	"MM": {"Myanmar (Burma)", "Myanmar (Burma)"},
	"MN": {"Mongolia", "Moğolistan"},
	"MO": {"Macao SAR China", "Çin Makao ÖİB"},
	"MP": {"Northern Mariana Islands", "Kuzey Mariana Adaları"},
	"MQ": {"Martinique", "Martinik"},
	"MR": {"Mauritania", "Moritanya"},
	"MS": {"Montserrat", "Montserrat"},
	"MT": {"Malta", "Malta"},
	"MU": {"Mauritius", "Mauritius"},
	"MV": {"Maldives", "Maldivler"},
	"MW": {"Malawi", "Malavi"},
	"MX": {"Mexico", "Meksika"},
	"MY": {"Malaysia", "Malezya"},
	"MZ": {"Mozambique", "Mozambik"},
	"NA": {"Namibia", "Namibya"},
	"NC": {"New Caledonia", "Yeni Kaledonya"},
	"NE": {"Niger", "Nijer"},
	"NF": {"Norfolk Island", "Norfolk Adası"},
	"NG": {"Nigeria", "Nijerya"},
	"NH": {"Vanuatu", "Vanuatu"},
	"NI": {"Nicaragua", "Nikaragua"},
	"NL": {"Netherlands", "Hollanda"},
	"NO": {"Norway", "Norveç"},
	"NP": {"Nepal", "Nepal"},
	"NR": {"Nauru", "Nauru"},
	"NU": {"Niue", "Niue"},
	"NZ": {"New Zealand", "Yeni Zelanda"},
	"OM": {"Oman", "Umman"},
	"PA": {"Panama", "Panama"},
	"PE": {"Peru", "Peru"},
	"PF": {"French Polynesia", "Fransız Polinezyası"},
	"PG": {"Papua New Guinea", "Papua Yeni Gine"},
	"PH": {"Philippines", "Filipinler"},
	"PK": {"Pakistan", "Pakistan"},
	"PL": {"Poland", "Polonya"},
	"PM": {"St. Pierre & Miquelon", "Saint Pierre ve Miquelon"},
	"PN": {"Pitcairn Islands", "Pitcairn Adaları"},
	"PR": {"Puerto Rico", "Porto Riko"},
	"PS": {"Palestinian Territories", "Filistin Bölgeleri"},
	"PT": {"Portugal", "Portekiz"},
	"PW": {"Palau", "Palau"},
	"PY": {"Paraguay", "Paraguay"},
	"QA": {"Qatar", "Katar"},
	"QO": {"Outlying Oceania", "Uzak Okyanusya"},
	"RE": {"Réunion", "Reunion"},
	"RH": {"Zimbabwe", "Zimbabve"},
	"RO": {"Romania", "Romanya"},
	"RS": {"Serbia", "Sırbistan"},
	"RU": {"Russia", "Rusya"},
	"RW": {"Rwanda", "Ruanda"},
	"SA": {"Saudi Arabia", "Suudi Arabistan"},
	"SB": {"Solomon Islands", "Solomon Adaları"},
	"SC": {"Seychelles", "Seyşeller"},
	"SD": {"Sudan", "Sudan"},
	"SE": {"Sweden", "İsveç"},
	"SG": {"Singapore", "Singapur"},
	"SH": {"St. Helena", "Saint Helena"},
	"SI": {"Slovenia", "Slovenya"},
	"SJ": {"Svalbard & Jan Mayen", "Svalbard ve Jan Mayen"},
	"SK": {"Slovakia", "Slovakya"},
	"SL": {"Sierra Leone", "Sierra Leone"},
	"SM": {"San Marino", "San Marino"},
	"SN": {"Senegal", "Senegal"},
	"SO": {"Somalia", "Somali"},
	"SR": {"Suriname", "Surinam"},
	"SS": {"South Sudan", "Güney Sudan"},
	"ST": {"São Tomé & Príncipe", "Sao Tome ve Principe"},
	"SU": {"Russia", "Rusya"},
	"SV": {"El Salvador", "El Salvador"},
	"SX": {"Sint Maarten", "Sint Maarten"},
	"SY": {"Syria", "Suriye"},
	"SZ": {"Eswatini", "Esvatini"},
	"TA": {"Tristan da Cunha", "Tristan da Cunha"},
	"TC": {"Turks & Caicos Islands", "Turks ve Caicos Adaları"},
	"TD": {"Chad", "Çad"},
	"TF": {"French Southern Territories", "Fransız Güney Toprakları"},
	"TG": {"Togo", "Togo"},
	"TH": {"Thailand", "Tayland"},
	"TJ": {"Tajikistan", "Tacikistan"},
	"TK": {"Tokelau", "Tokelau"},
	"TL": {"Timor-Leste", "Timor-Leste"},
	"TM": {"Turkmenistan", "Türkmenistan"},
	"TN": {"Tunisia", "Tunus"},
	"TO": {"Tonga", "Tonga"},
	"TP": {"Timor-Leste", "Timor-Leste"},
	"TR": {"Türkiye", "Türkiye"},
	"TT": {"Trinidad & Tobago", "Trinidad ve Tobago"},
	"TV": {"Tuvalu", "Tuvalu"},
	"TW": {"Taiwan", "Tayvan"},
	"TZ": {"Tanzania", "Tanzanya"},
	"UA": {"Ukraine", "Ukrayna"},
	"UG": {"Uganda", "Uganda"},
	"UK": {"United Kingdom", "Birleşik Krallık"},
	"UM": {"U.S. Outlying Islands", "ABD Küçük Harici Adaları"},
	"UN": {"United Nations", "Birleşmiş Milletler"},
	"US": {"United States", "Amerika Birleşik Devletleri"},
	"UY": {"Uruguay", "Uruguay"},
	"UZ": {"Uzbekistan", "Özbekistan"},
	"VA": {"Vatican City", "Vatikan"},
	"VC": {"St. Vincent & Grenadines", "Saint Vincent ve Grenadinler"},
	"VD": {"Vietnam", "Vietnam"},
	"VE": {"Venezuela", "Venezuela"},
	"VG": {"British Virgin Islands", "Britanya Virjin Adaları"},
	"VI": {"U.S. Virgin Islands", "ABD Virjin Adaları"},
	"VN": {"Vietnam", "Vietnam"},
	"VU": {"Vanuatu", "Vanuatu"},
	"WF": {"Wallis & Futuna", "Wallis ve Futuna"},
	"WS": {"Samoa", "Samoa"},
	"XA": {"Pseudo-Accents", "Psödo Aksanlar"},
	"XB": {"Pseudo-Bidi", "Psödo Bidi"},
	"XK": {"Kosovo", "Kosova"},
	"YD": {"Yemen", "Yemen"},
	"YE": {"Yemen", "Yemen"},
	"YT": {"Mayotte", "Mayotte"},
	"YU": {"Serbia", "Sırbistan"},
	"ZA": {"South Africa", "Güney Afrika"},
	"ZM": {"Zambia", "Zambiya"},
	"ZR": {"Congo - Kinshasa", "Kongo - Kinşasa"},
	"ZW": {"Zimbabwe", "Zimbabve"},
	"ZZ": {"Unknown Region", "Bilinmeyen Bölge"},
}

func CountryEN(iso string) string {
	if v, ok := countryNames[iso]; ok {
		return v[0]
	}
	return iso
}

func CountryTR(iso string) string {
	if v, ok := countryNames[iso]; ok {
		return v[1]
	}
	return iso
}
